### ISSUE TITLE
make all the links work without referring to the live fresyesrealtor.com site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/fresyesrealtor#2]
First off, go to the buildicus drive and upload the v2 folder to github and then make a gh-pages branch. 

Make sure all links are relative and do not use any PHP at all since gh-pages doesn't parse PHP. 

due:
8-24-15   12p

**Comment by purplyrocky** [comment]
So i changed the paths on the about page and saved but when i click on the links, they still try and take you to the live site so the page can not be found because the live site is already down.

**Comment by rodneystrong** [comment]
Hmm.. 

Do me a favor and upload your code here. Create a gh-pages branch and try to get everything to load similarly to how it loads locally for you. 

Once you've done that I'll look into why the links are absolute.

due:
8-25-15 11p

**Comment by purplyrocky** [comment]
done and pushed to both master and gh-pages 931dcb7cffb81c707b682bfe55d3f579737a3cfe

The links just add the "/about.html" path that i added to the end of the domain

**Comment by rodneystrong** [comment]
OH WOW I FIGURED IT OUT!  

Dude it's fuckin crazy; just for kicks, I looked at the ````<head>```` section and noticed this ````<base>```` tag I've never seen before. This is what the code was: 
````<base href="http://www.fresyesrealtor.com/">````

I thought to myself, "What the fuck does this deductively mean?! This has GOT to be why all the links are absolute to fresyesrealtor.com even though Raquel made them all relative". 

Sure enough, I double-checked with documentation from 2 different online sources and the ````<base>```` tag does exactly that, force all links to be absolute to the specified URL. 

#winning

**Comment by purplyrocky** [comment]
@rodneystrong awesome find, glad you could help. I downloaded 21 pages for that site and there are about 30 links per page that I had to go through and try to make relative. So when I saw it didn't work, I was pretty much too frustrated to keep looking for the issue so I really appreciate your help on this.

**Comment by rodneystrong** [comment]
@purplyrocky I COMPLETELY understand.. I would've ended up getting frustrated as well and forcing myself to walk away and not look at it again for at least a day.
