### ISSUE TITLE
Remove <base> tag in the <head>

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/fresyesrealtor#3]
As discovered in issue #2 , delete the ````<base>```` tag. 

Also, make all the resources relative as well. Basically I want you to pull all the files the site is referencing through CSS and JS and create a 'css' and 'js' folder and structure the site the exact way you'd do it if you were to create it from scratch. 

Then you'll need to update the links on all the pages to reflect correctly on their new relative paths. 

Do this for all the images as well (create an 'img' folder and put all the images there and then update the links to be relative to that folder)

due:
8-29-15  10p

**Comment by purplyrocky** [comment]
When I removed the < base > tag, it completely broke the page so this is going to take longer than expected since there are 21 pages that i now have to go through and look for the links that are breaking 
:(
new due date:
8-31-15 11pm

**Comment by purplyrocky** [comment]
@rodneystrong I was moving all the files into a js/css/img folder and I left the < base > tag in the head and when I refreshed the page, everything is still in tact so the pages were never pulling the styles from those files, i think it's because we copied the source after downloading the site didn't work

**Comment by purplyrocky** [comment]
It's also not grabbing the background color of the nav, the gradient background and the background colors for the heading items in the sidebars. I'm not going to push until you tell me it's okay because the pages look way different now.

**Comment by rodneystrong** [comment]
@purplyrocky  Hmm... please push this to master as soon as you can so I can take a look. 

Don't push this to gh-pages just yet, just master ASAP. Thanks!

**Comment by purplyrocky** [comment]
It's pushed.

**Comment by rodneystrong** [comment]
Ah.. turns it out was using a series of background images to display those different shades of gray.. 

I'll look for the relative links in both yours and meg's versions and fix this.
